# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-04 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0003_auto_20190804_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mobilenumber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
